-- ============================================================================
-- DATABASE SCHEMA
-- ============================================================================
-- TODO for Database Team:
-- Run this script in your MySQL Workbench to set up the project tables.
-- ============================================================================

-- 1. Create Database
CREATE DATABASE IF NOT EXISTS face_attendance_db;
USE face_attendance_db;

-- 2. Table: Students
-- TODO: We need to store the student's details.
-- Note: 'face_encoding' will store the long blob/text data generated by Python.
-- CREATE TABLE students (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     full_name VARCHAR(100) NOT NULL,
--     enrollment_number VARCHAR(50) UNIQUE NOT NULL,
--     face_encoding TEXT,  -- This stores the face data
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- 3. Table: Attendance Logs
-- TODO: This tracks when a student was seen by the camera.
-- CREATE TABLE attendance_logs (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     student_id INT,
--     scan_time DATETIME DEFAULT CURRENT_TIMESTAMP,
--     status VARCHAR(20) DEFAULT 'Present',
--     FOREIGN KEY (student_id) REFERENCES students(id)
-- );

-- 4. Insert Dummy Data
-- TODO: Add one fake student so we can test the app later.